# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bbrassar <bbrassar@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/27 17:34:44 by bbrassar          #+#    #+#              #
#    Updated: 2023/11/27 17:35:59 by bbrassar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RM := rm -vf

.PHONY: all clean fclean re

all: Colleen.py Grace.py Sully.py

clean fclean:
	@$(RM) Grace_kid.py Sully_*.py

re: fclean all
