# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: bbrassar <bbrassar@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/28 09:07:17 by bbrassar          #+#    #+#              #
#    Updated: 2023/11/28 09:07:38 by bbrassar         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RM := rm -vf

.PHONY: all clean fclean re

all: Colleen.pl Grace.pl Sully.pl

clean fclean:
	@$(RM) Grace_kid.pl Sully_*.pl

re: fclean all
